name: publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    if: github.repository == 'ArchiDep/website'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # https://github.com/docker/login-action
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for the app image
        id: app-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/archidep/app
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      # https://github.com/docker/build-push-action
      - name: Build and push the app image
        id: app-push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: app
          push: true
          tags: ${{ steps.app-meta.outputs.tags }}
          labels: ${{ steps.app-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/archidep/app:latest
          cache-to: type=inline

      # https://github.com/actions/attest-build-provenance
      - name: Generate artifact attestation for the app image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/archidep/app
          subject-digest: ${{ steps.app-push.outputs.digest }}
          push-to-registry: true

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for the assets image
        id: assets-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/archidep/assets
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}

      # https://github.com/docker/build-push-action
      - name: Build and push the assets image
        id: assets-push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: assets-server
          push: true
          tags: ${{ steps.assets-meta.outputs.tags }}
          labels: ${{ steps.assets-meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/archidep/assets:latest
          cache-to: type=inline

      # https://github.com/actions/attest-build-provenance
      - name: Generate artifact attestation for the assets image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/archidep/assets
          subject-digest: ${{ steps.assets-push.outputs.digest }}
          push-to-registry: true
